POST http://127.0.0.1:8000/conversations

###

POST http://127.0.0.1:8000/conversations/{conversation_id}/message
Content-Type: application/json

{
    "question": "What is the first question I asked you?"
}

###

POST http://127.0.0.1:8000/conversations/{conversation_id}/message-stream
Content-Type: application/json

{
    "question": "What is the size of the Great Wall of China?"
}

curl -N -X POST http://127.0.0.1:8000/conversations/{conversation_id}/message-stream \
  -H "Content-Type: application/json" \
  -d '{"question": "What is the size of the Great Wall of China?"}'

###

curl -N -X POST http://127.0.0.1:8000/conversations/{conversation_id}/message-stream-all \
  -H "Content-Type: application/json" \
  -d '{"question": "What is the size of the Great Wall of China?"}'
